# Generated by Django 5.1.4 on 2025-06-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('actor1', models.CharField(blank=True, max_length=100, verbose_name='Actor/Actress 1')),
                ('actor2', models.CharField(blank=True, max_length=100, verbose_name='Actor/Actress 2')),
                ('actor3', models.CharField(blank=True, max_length=100, verbose_name='Actor/Actress 3')),
                ('actor4', models.CharField(blank=True, max_length=100, verbose_name='Actor/Actress 4')),
                ('poster_url', models.URLField(blank=True, verbose_name='Poster URL')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
