# Generated by Django 5.1.4 on 2025-06-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Sci-fi', 'Sci-fi'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Adventure', 'Adventure'), ('Biography', 'Biography')], default='Drama', max_length=20),
        ),
    ]
